[build]
jobs = 8
rustflags = [
    "-C", "strip=symbols",
    "-C", "debuginfo=0",
    "-C", "panic=abort",
    "-Z", "location-detail=none",
    "-C", "opt-level=z",
    "-C", "codegen-units=1",
    "-C", "lto=fat",
    "-C", "force-frame-pointers=no",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo\\registry\\src=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo\\registry=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo\\git=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.cargo=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.rustup\\toolchains=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\.rustup=.",
    "--remap-path-prefix", "C:\\path\\to\\ferrox=.",
    "--remap-path-prefix", "C:\\path\\to=.",
    "--remap-path-prefix", "C:\\path=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername\\AppData=.",
    "--remap-path-prefix", "C:\\Users\\YourUsername=.",
    "--remap-path-prefix", "src/wallet=/dev/null",
    "--remap-path-prefix", "src\\wallet=/dev/null",
    "--remap-path-prefix", "src/app=/dev/null",
    "--remap-path-prefix", "src\\app=/dev/null",
    "--remap-path-prefix", "src/docs=/dev/null",
    "--remap-path-prefix", "src\\docs=/dev/null",
    "--remap-path-prefix", "src/communications=/dev/null",
    "--remap-path-prefix", "src\\communications=/dev/null",
    "--remap-path-prefix", "src/fun/games=/dev/null",
    "--remap-path-prefix", "src\\fun\\games=/dev/null",
    "--remap-path-prefix", "src/fun=/dev/null",
    "--remap-path-prefix", "src\\fun=/dev/null",
    "--remap-path-prefix", "src/proc/browser=/dev/null",
    "--remap-path-prefix", "src\\proc\\browser=/dev/null",
    "--remap-path-prefix", "src/proc/lbrowser=/dev/null",
    "--remap-path-prefix", "src\\proc\\lbrowser=/dev/null",
    "--remap-path-prefix", "src/proc/system=/dev/null",
    "--remap-path-prefix", "src\\proc\\system=/dev/null",
    "--remap-path-prefix", "src/proc=/dev/null",
    "--remap-path-prefix", "src\\proc=/dev/null",
    "--remap-path-prefix", "src/bin=/dev/null",
    "--remap-path-prefix", "src\\bin=/dev/null",
    "--remap-path-prefix", "src\\fingerprint.rs=/dev/null",
    "--remap-path-prefix", "src/fingerprint.rs=/dev/null",
    "--remap-path-prefix", "src\\detection.rs=/dev/null",
    "--remap-path-prefix", "src/detection.rs=/dev/null",
    "--remap-path-prefix", "src\\stealth.rs=/dev/null",
    "--remap-path-prefix", "src/stealth.rs=/dev/null",
    "--remap-path-prefix", "src\\api_resolve.rs=/dev/null",
    "--remap-path-prefix", "src/api_resolve.rs=/dev/null",
    "--remap-path-prefix", "src\\ntbridge.rs=/dev/null",
    "--remap-path-prefix", "src/ntbridge.rs=/dev/null",
    "--remap-path-prefix", "src\\padding.rs=/dev/null",
    "--remap-path-prefix", "src/padding.rs=/dev/null",
    "--remap-path-prefix", "src\\polymorph.rs=/dev/null",
    "--remap-path-prefix", "src/polymorph.rs=/dev/null",
    "--remap-path-prefix", "src\\recon.rs=/dev/null",
    "--remap-path-prefix", "src/recon.rs=/dev/null",
    "--remap-path-prefix", "src\\cleanup.rs=/dev/null",
    "--remap-path-prefix", "src/cleanup.rs=/dev/null",
    "--remap-path-prefix", "src\\dissolve.rs=/dev/null",
    "--remap-path-prefix", "src/dissolve.rs=/dev/null",
    "--remap-path-prefix", "src\\ntcall.rs=/dev/null",
    "--remap-path-prefix", "src/ntcall.rs=/dev/null",
    "--remap-path-prefix", "src\\system_health.rs=/dev/null",
    "--remap-path-prefix", "src/system_health.rs=/dev/null",
    "--remap-path-prefix", "src\\sprotect.rs=/dev/null",
    "--remap-path-prefix", "src/sprotect.rs=/dev/null",
    "--remap-path-prefix", "src\\win_internals.rs=/dev/null",
    "--remap-path-prefix", "src/win_internals.rs=/dev/null",
    "--remap-path-prefix", "src\\api_hash.rs=/dev/null",
    "--remap-path-prefix", "src/api_hash.rs=/dev/null",
    "--remap-path-prefix", "src\\main.rs=/dev/null",
    "--remap-path-prefix", "src/main.rs=/dev/null",
    "--remap-path-prefix", "src\\lib.rs=/dev/null",
    "--remap-path-prefix", "src/lib.rs=/dev/null",
    "--remap-path-prefix", "src/=/dev/null",
    "--remap-path-prefix", "src\\=/dev/null",
    "--remap-path-prefix", "/c/Users/YourUsername/.cargo=/dev/null",
    "--remap-path-prefix", "/c/Users/YourUsername/.rustup=/dev/null",
    "--remap-path-prefix", "/c/path/to/ferrox=/dev/null",
    "--remap-path-prefix", "/c/path/to=/dev/null",
    "--remap-path-prefix", "/c/Users/YourUsername=/dev/null",
    "-C", "link-arg=/PDBALTPATH:/dev/null",
    "-C", "link-arg=/DEBUG:NONE",
    "-C", "link-arg=/PDBSTRIPPED",
    "-C", "link-arg=/SUBSYSTEM:WINDOWS",
    "-C", "link-arg=/ENTRY:mainCRTStartup",
    "-C", "link-arg=/MANIFEST:NO"
]
